name: "Deploy new forms version, do not forget to change encoding"

on:
  push:
    branches-ignore:    
      - 'feat/**'

jobs:
  ci-build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Configure S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: "eu-central-1"

      - name: Install modules
        run: npm ci

      - name: Bundle JS
        run: ./node_modules/.bin/webpack --env mode=production REACT_APP_TENANT=${{ steps.extract_branch.outputs.branch }} REACT_APP_BACKEND=${{secrets.REACT_APP_BACKEND}} REACT_APP_API_TOKEN=${{secrets.REACT_APP_API_TOKEN}} REACT_APP_GAPI_KEY={{secrets.REACT_APP_GAPI_KEY}} REACT_APP_POOL_ID={{secrets.REACT_APP_POOL_ID}}

      - name: Rename gzipped file
        run: npm run rename

      - name: Upload to aws
        run: aws s3 sync ./dist s3://forms.sputnyq.de/${{ steps.extract_branch.outputs.branch }}
